### ISSUE TITLE
NameError: name 'basestring' is not defined

### ISSUE THREAD

**Issue by elda27** [pylablanche/gcForest#6]
I want to test gcForest so I used tools/train_fg.py according to README. 
But the error indicated at the title occurs. 
The detail of error message is following below.

>  File "tools/train_fg.py", line 48, in <module>
>    net = FGNet(config["net"], train_config.data_cache)
>  File "lib\gcforest\fgnet.py", line 36, in __init__
>    layer = get_layer(layer_config, self.data_cache)
>  File "lib\gcforest\layers\__init__.py", line 32, in get_layer
>    layer = layer_class(layer_config, data_cache)
>  File "lib\gcforest\layers\fg_pool_layer.py", line 27, in __init__
>    self.pool_method = self.get_value("pool_method", "avg", basestring)
>	NameError: name 'basestring' is not defined

Does this error cause my environment?
Or does it cause bad implementation?

--Appendix information--

I ran following command in the root directory of gcForest. (This command is noted at line 168 about README)

> python tools/train_fg.py --model models/mnist/gcforest/fg-tree500-depth100-3folds.json --log_dir logs/gcforest/mnist/fg --save_outputs

And my environment is following here.

- Python 3.6 (Anaconda 4.4.0)
- Windows 10 64bit

**Comment by elda27** [comment]
I'm so sorry. 
I posted to wrong repository.

**Comment by pylablanche** [comment]
@elda27 No problems
