### ISSUE TITLE
completely-random tree forests

### ISSUE THREAD

**Issue by sevenguin** [pylablanche/gcForest#7]
There are two types of forest in the paper, and the first is completely-random tree forests. I think the forest is show in code
 `crf = RandomForestClassifier(n_estimators=n_tree, max_features=None, min_samples_split=min_samples, oob_score=True, n_jobs=n_jobs)` , in function `window_slicing_pred_prob`, if i'm right, then the parameter max_features should be 1.

**Comment by pylablanche** [comment]
Hi @sevenguin ,
Thanks for you comment. I went back to the documentation and indeed setting max_features to 1 makes the classifier a totally random decision tree [see documentation](http://scikit-learn.org/stable/modules/generated/sklearn.tree.ExtraTreeClassifier.html#sklearn.tree.ExtraTreeClassifier). I am now confused about what the deep forest authors meant by "completely random forest".
I'll go back to the paper and make corrections if I misunderstood this part.

Thanks again for the feedback

**Comment by pylablanche** [comment]
@sevenguin ,
I have double checked the paper and the scikit documentation and you're right about the max_features. It's now corrected and updated.
Thanks for noticing!!!
